name: tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        vscode-version: ['1.104.0', '1.110.0']
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: |
          npm i -g pnpm
          pnpm i

      - run: pnpm run lint
        if: matrix.os == 'ubuntu-latest' # Run only once

      - run: pnpm run test:unit
        if: matrix.os == 'ubuntu-latest' # Run only once

      - run: pnpm run test:benchmark
        if: matrix.os == 'ubuntu-latest' # Run only once

      - name: Install Screenshot Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y x11-apps imagemagick

      - name: Run VS Code Extension Tests
        if: runner.os == 'Linux'
        run: |
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          pnpm run test:vsc
        env:
          VSCODE_VERSION: ${{ matrix.vscode-version }}

      - name: Upload Failing Test Screenshots Linux
        if: failure() && runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: failing-tests-screenshots-${{ matrix.os }}-${{ matrix.vscode-version }}
          path: /tmp/vscode_sort_json_*.png
          if-no-files-found: ignore

      - name: Run VS Code Extension Tests
        if: runner.os != 'Linux'
        run: npm run test:vsc
        env:
          VSCODE_VERSION: ${{ matrix.vscode-version }}

      - name: Upload Failing Test Screenshots Windows
        if: failure() && runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: failing-tests-screenshots-${{ matrix.os }}-${{ matrix.vscode-version }}
          path: ~\AppData\Local\Temp\vscode_sort_json_*.png
          if-no-files-found: ignore
